// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Client struct {
	ID        string `json:"id"`
	Name      string `json:"Name"`
	ProductID string `json:"Product_Id"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Product struct {
	ID   string `json:"id"`
	Name string `json:"Name"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
